name: shopping_app
description: A simple shopping app with product list, cart, and checkout.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
    - assets/background_icon.png

flutter_launcher_icons:
  android: true  # Chỉ tạo icon cho Android
  ios: false     # Bỏ qua iOS
  image_path: "assets/background_icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/background_icon.png"